Hw03 mongodb
OleksiiMaistriuk/nodejs-homeworks pull request #2
Opened 2021-05-16 12:20 UTC by OleksiiMaistriuk

2021-05-17 20:16 UTC, SergeiKBB requested changes

2021-05-17 20:16 UTC, SergeiKBB commented on .env
> +URI_DB=mongodb+srv://drankel:drankel0@cluster0.q033s.mongodb.net/db-contacts?retryWrites=true&w=majority
этот файл должен быть в игноре

2021-05-18 12:08 UTC, OleksiiMaistriuk commented on .env
> +URI_DB=mongodb+srv://drankel:drankel0@cluster0.q033s.mongodb.net/db-contacts?retryWrites=true&w=majority
исправил

2021-05-18 19:46 UTC, SergeiKBB commented on .env
> +URI_DB=mongodb+srv://drankel:drankel0@cluster0.q033s.mongodb.net/db-contacts?retryWrites=true&w=majority
с ремоут репозитория его тоже нужно удалить

2021-05-18 20:04 UTC, OleksiiMaistriuk commented on .env
> +URI_DB=mongodb+srv://drankel:drankel0@cluster0.q033s.mongodb.net/db-contacts?retryWrites=true&w=majority
не знаю как это сделать

2021-05-19 20:44 UTC, SergeiKBB approved these changes

2021-05-19 21:22 UTC, merged