закончил дз
OleksiiMaistriuk/nodejs-homeworks pull request #5
Opened 2021-06-15 20:48 UTC by OleksiiMaistriuk

2021-06-16 22:49 UTC, SergeiKBB requested changes

2021-06-16 22:49 UTC, SergeiKBB commented on coverage/clover.xml
> +      <metrics statements="15" coveredstatements="7" conditionals="4" coveredconditionals="0" methods="1" coveredmethods="0"/>
coverage нужно добавить в гитигнор

2021-06-17 15:49 UTC, OleksiiMaistriuk commented on coverage/clover.xml
> +      <metrics statements="15" coveredstatements="7" conditionals="4" coveredconditionals="0" methods="1" coveredmethods="0"/>
добавил

2021-06-17 15:53 UTC, OleksiiMaistriuk commented on coverage/clover.xml
> +      <metrics statements="15" coveredstatements="7" conditionals="4" coveredconditionals="0" methods="1" coveredmethods="0"/>
удалил из гита

2021-06-18 15:09 UTC, SergeiKBB approved these changes

2021-06-20 17:01 UTC, merged